### ISSUE TITLE
Release v2.0.2 does not work in Windows 10

### ISSUE THREAD

**Issue by pharant** [bigclownlabs/bc-windows-ide#1]
There is an error after instalation:

Unable to execute file:
C:\BigClown\usr\bin\bci.cmd

CreateProcess failed; code 267.
Název adresáře je neplatný

**Comment by pharant** [comment]
Asi chyba v nastavení cest.
Když jsem v **c:\BigClown\usr\bin\bci.cmd** změnil **code** na **"c:\Program Files (x86)\Microsoft VS Code\Code.exe"** , tak se už spouští.

**Comment by pharant** [comment]
Vyřešeno přidáním **"c:\Program Files (x86)\Microsoft VS Code\"** do PATH, už to funguje i včetně kompilace.

**Comment by hubpav** [comment]
Mockrát díky za report. Prosím @muhlpachr o reakci.

**Comment by muhlpachr** [comment]
Díky za info.
Prosím byl VSCode instalován někdy před instalací IDE nebo bylo po instalaci IDE modifikováno nastavení Path environment proměnné ?
Nenapadá mě, jak jinak by mohla instalace VSCode skončit bez přidání cesty do Path. V instalaci IDE se pouští originální instalátor https://github.com/bigclownlabs/bc-windows-ide/blob/master/bc-windows-ide.iss#L83, který přidává díky task addtopath do Path standardně C:\Program Files (x86)\Microsoft VS Code\bin odkud příkaz code spouští code.cmd
Prosím můžete z cmd vypsat výsledek dvou příkazů:
echo %Path%
a
reg query HKEY_CLASSES_ROOT\VSCodeSourceFile\shell\open\command
Děkuji.

**Comment by pharant** [comment]
Ahoj,
VSCode předtím nebyl instalován.

C:\Users\Harry>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
Files (x86)\Skype\Phone\;C:\Program Files\TortoiseHg\;C:\Program
Files\TortoiseGit\bin;C:\Program Files\PuTTY\;C:\Program Files
(x86)\nodejs\;C:\Program Files (x86)\Microsoft VS
Code\;C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Harry\AppData\Local\Programs\Python\Python36-32\;C:\Users\Harry\AppData\Local\Microsoft\WindowsApps;

Cestu na VSCode jsem tam přidával ručně a poté jsem ještě instaloval ten
Python.

C:\Users\Harry>reg query
HKEY_CLASSES_ROOT\VSCodeSourceFile\shell\open\command

HKEY_CLASSES_ROOT\VSCodeSourceFile\shell\open\command
    (Default)    REG_SZ    "C:\Program Files (x86)\Microsoft VS
Code\Code.exe" "%1"

Petr

2017-03-11 1:24 GMT+01:00 Michal Mühlpachr <notifications@github.com>:

**Comment by muhlpachr** [comment]
Díky za info.
Nenapadá mě, proč instalace VSCode nepřidala do Path - možná překročení limitu délky Path.
Vyřeším to otestováním, zda code najde v cestě a když ne, vezmu cestu z registry a použiji pro spuštění VSCode.

**Comment by muhlpachr** [comment]
Vyřešeno ve v2.1.0
